import { PackageDescriptionProps } from 'src/types/external/api';

export const packageDescriptionMock: PackageDescriptionProps[] = [
  {
    image: [
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/fortaleza/fortaleza_1.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/fortaleza/fortaleza_2.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/fortaleza/fortaleza_3.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/fortaleza/fortaleza_4.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/fortaleza/fortaleza_5.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/fortaleza/fortaleza_6.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/fortaleza/fortaleza_7.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/fortaleza/fortaleza_8.jpg' },
    ],
    title: 'Fortaleza',
    subtitle: 'Ibis Budget Praia de Iracema',
    content: [
      { icon: 'plane', text: 'Aéreo saindo de Uberlândia' },
      { icon: 'sun', text: '8 dias' },
      { icon: 'calendar', text: 'De 27/04/2024 à 04/05/2024' },
      { icon: 'coffee', text: 'Café da manhã incluso' },
      { icon: 'bell_concierge', text: 'Hotel Ibis Budget' },
    ],
    price: 1908.2,
    split: '10x',
    splitValue: 170.83,
    descriptionText: 'Valor por pessoa',
    upfront: 'Valor de entrada: R$ 200,00',
    // items: [
    //   'Piscina ao ar livre',
    //   'Quartos para não fumantes',
    //   'Serviço de quarto',
    //   'Estacionamento gratuito',
    //   'Wi-Fi gratuito',
    //   'Beira-mar',
    // ],
  },
  {
    image: [
      {
        name: '',
        publicUrl: 'https://storage.googleapis.com/lazertur/porto_galinhas/porto_galinhas_1.png',
      },
      {
        name: '',
        publicUrl: 'https://storage.googleapis.com/lazertur/porto_galinhas/porto_galinhas_2.jpg',
      },
      {
        name: '',
        publicUrl: 'https://storage.googleapis.com/lazertur/porto_galinhas/porto_galinhas_3.jpg',
      },
      {
        name: '',
        publicUrl: 'https://storage.googleapis.com/lazertur/porto_galinhas/porto_galinhas_4.jpg',
      },
      {
        name: '',
        publicUrl: 'https://storage.googleapis.com/lazertur/porto_galinhas/porto_galinhas_5.png',
      },
      {
        name: '',
        publicUrl: 'https://storage.googleapis.com/lazertur/porto_galinhas/porto_galinhas_6.png',
      },
      {
        name: '',
        publicUrl: 'https://storage.googleapis.com/lazertur/porto_galinhas/porto_galinhas_7.png',
      },
    ],
    title: 'Porto de Galinhas',
    subtitle: 'Pousada Capitães de Areia',
    content: [
      { icon: 'sun', text: '8 dias' },
      { icon: 'plane', text: 'Aéreo saindo de Uberlândia' },
      { icon: 'calendar', text: 'De 25/05/24 à 01/06/24' },
      { icon: 'coffee', text: 'Café da manhã incluso' },
    ],
    price: 2154.07,
    split: '10x',
    splitValue: 175.41,
    descriptionText: 'Valor por pessoa',
    upfront: 'Valor de entrada: R$ 400,00',
    // items: [
    //   'Piscina ao ar livre',
    //   'Quartos para não fumantes',
    //   'Serviço de quarto',
    //   'Estacionamento gratuito',
    //   'Wi-Fi gratuito',
    //   'Beira-mar',
    // ],
  },

  {
    image: [
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/ilheus/ilheus_1.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/ilheus/ilheus_2.webp' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/ilheus/ilheus_3.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/ilheus/ilheus_4.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/ilheus/ilheus_5.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/ilheus/ilheus_6.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/ilheus/ilheus_7.jpeg' },
    ],
    title: 'Ilhéus - BA',
    subtitle: 'Indaiá Eco Village',
    content: [
      { icon: 'sun', text: '6 dias' },
      { icon: 'plane', text: 'Aéreo saindo de Uberlândia' },
      { icon: 'calendar', text: 'De 20/10/24 à 26/10/24' },
      { icon: 'coffee', text: 'Café da manhã incluso' },
    ],
    price: 2298.8,
    split: '10x',
    splitValue: 189.88,
    descriptionText: 'Valor por pessoa',
    upfront: 'Valor de entrada: R$ 400,00',
    // items: [
    //   'Piscina ao ar livre',
    //   'Quartos para não fumantes',
    //   'Serviço de quarto',
    //   'Estacionamento gratuito',
    //   'Wi-Fi gratuito',
    //   'Beira-mar',
    // ],
  },
  {
    image: [
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/bonito/bonito_1.webp' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/bonito/bonito_2.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/bonito/bonito_3.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/bonito/bonito_4.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/bonito/bonito_5.webp' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/bonito/bonito_6.jpg' },
      { name: '', publicUrl: 'https://storage.googleapis.com/lazertur/bonito/bonito_7.jpg' },
    ],
    title: 'Bonito - MS',
    subtitle: 'Pousada Muito bonito',
    content: [
      { icon: 'sun', text: '7 dias' },
      { icon: 'plane', text: 'Aéreo saindo de Uberlândia' },
      { icon: 'calendar', text: 'De 18/08/24 à 24/08/24' },
      { icon: 'coffee', text: 'Café da manhã incluso' },
    ],
    price: 2802.19,
    split: '10x',
    splitValue: 240.22,
    descriptionText: 'Valor por pessoa',
    upfront: 'Valor de entrada: R$ 400,00',
    // items: [
    //   'Piscina ao ar livre',
    //   'Quartos para não fumantes',
    //   'Serviço de quarto',
    //   'Estacionamento gratuito',
    //   'Wi-Fi gratuito',
    //   'Beira-mar',
    // ],
  },
  // {
  //   image: ['/assets/images/highlight-packages/gramado.png'],
  //   title: 'Gramado - RS',
  //   subtitle: 'Hotel Cabanas Jardim de Flores',
  //   content: [
  //     { icon: 'sun', text: '4 dias' },
  //     { icon: 'plane', text: 'Aéreo saindo de Uberlândia' },
  //     { icon: 'calendar', text: 'De 10/06/24 à 14/06/24' },
  //     { icon: 'coffee', text: 'Café da manhã incluso' },
  //   ],
  //   price: 2420.59,
  //   oldPrice: 2000.0,
  //   split: '10x',
  //   splitValue: 202.06,
  //   descriptionText: 'Valor por pessoa',
  //   upfront: 'Valor de entrada: R$ 400,00',
  //   items: [
  //     'Piscina ao ar livre',
  //     'Quartos para não fumantes',
  //     'Serviço de quarto',
  //     'Estacionamento gratuito',
  //     'Wi-Fi gratuito',
  //     'Beira-mar',
  //   ],
  // },
];
