import { PackageDescriptionProps } from 'src/types/external/api';

export const packageDescriptionMock: PackageDescriptionProps[] = [
  {
    image: ['/assets/images/highlight-packages/fortaleza.png'],
    title: 'Fortaleza',
    subtitle: 'Ibis Budget Praia de Iracema',
    content: [
      { icon: 'plane', text: 'Aéreo saindo de Uberlândia' },
      { icon: 'sun', text: '8 dias' },
      { icon: 'calendar', text: 'De 27/04/2024 à 04/05/2024' },
      { icon: 'coffee', text: 'Café da manhã incluso' },
      { icon: 'bell_concierge', text: 'Hotel Ibis Budget' },
    ],
    price: 1908.2,
    oldPrice: 2000.0,
    split: '10x',
    splitValue: 170.83,
    descriptionText: 'Valor por pessoa',
    upfront: 'Valor de entrada: R$ 200,00',
    items: [
      'Piscina ao ar livre',
      'Quartos para não fumantes',
      'Serviço de quarto',
      'Estacionamento gratuito',
      'Wi-Fi gratuito',
      'Beira-mar',
    ],
  },
  {
    image: ['/assets/images/highlight-packages/porto_galinhas.png'],
    title: 'Porto de Galinhas',
    subtitle: 'Pousada Capitães de Areia',
    content: [
      { icon: 'sun', text: '8 dias' },
      { icon: 'plane', text: 'Aéreo saindo de Uberlândia' },
      { icon: 'calendar', text: 'De 25/05/24 à 01/06/24' },
      { icon: 'coffee', text: 'Café da manhã incluso' },
    ],
    price: 2154.07,
    oldPrice: 2000.0,
    split: '10x',
    splitValue: 175.41,
    descriptionText: 'Valor por pessoa',
    upfront: 'Valor de entrada: R$ 400,00',
    items: [
      'Piscina ao ar livre',
      'Quartos para não fumantes',
      'Serviço de quarto',
      'Estacionamento gratuito',
      'Wi-Fi gratuito',
      'Beira-mar',
    ],
  },
  // {
  //   image: ['/assets/images/highlight-packages/gramado.png'],
  //   title: 'Gramado - RS',
  //   subtitle: 'Hotel Cabanas Jardim de Flores',
  //   content: [
  //     { icon: 'sun', text: '4 dias' },
  //     { icon: 'plane', text: 'Aéreo saindo de Uberlândia' },
  //     { icon: 'calendar', text: 'De 10/06/24 à 14/06/24' },
  //     { icon: 'coffee', text: 'Café da manhã incluso' },
  //   ],
  //   price: 2420.59,
  //   oldPrice: 2000.0,
  //   split: '10x',
  //   splitValue: 202.06,
  //   descriptionText: 'Valor por pessoa',
  //   upfront: 'Valor de entrada: R$ 400,00',
  //   items: [
  //     'Piscina ao ar livre',
  //     'Quartos para não fumantes',
  //     'Serviço de quarto',
  //     'Estacionamento gratuito',
  //     'Wi-Fi gratuito',
  //     'Beira-mar',
  //   ],
  // },
  {
    image: ['/assets/images/highlight-packages/fortaleza/fortaleza_1.jpg'],
    title: 'Ilhéus - BA',
    subtitle: 'Indaiá Eco Village',
    content: [
      { icon: 'sun', text: '6 dias' },
      { icon: 'plane', text: 'Aéreo saindo de Uberlândia' },
      { icon: 'calendar', text: 'De 20/10/24 à 26/10/24' },
      { icon: 'coffee', text: 'Café da manhã incluso' },
    ],
    price: 2298.8,
    oldPrice: 2000.0,
    split: '10x',
    splitValue: 189.88,
    descriptionText: 'Valor por pessoa',
    upfront: 'Valor de entrada: R$ 400,00',
    items: [
      'Piscina ao ar livre',
      'Quartos para não fumantes',
      'Serviço de quarto',
      'Estacionamento gratuito',
      'Wi-Fi gratuito',
      'Beira-mar',
    ],
  },
  {
    image: ['/assets/images/highlight-packages/fortaleza.png'],
    title: 'Bonito - MS',
    subtitle: 'Pousada Muito bonito',
    content: [
      { icon: 'sun', text: '7 dias' },
      { icon: 'plane', text: 'Aéreo saindo de Uberlândia' },
      { icon: 'calendar', text: 'De 18/08/24 à 24/08/24' },
      { icon: 'coffee', text: 'Café da manhã incluso' },
    ],
    price: 2802.19,
    oldPrice: 2000.0,
    split: '10x',
    splitValue: 240.22,
    descriptionText: 'Valor por pessoa',
    upfront: 'Valor de entrada: R$ 400,00',
    items: [
      'Piscina ao ar livre',
      'Quartos para não fumantes',
      'Serviço de quarto',
      'Estacionamento gratuito',
      'Wi-Fi gratuito',
      'Beira-mar',
    ],
  },
];
