// ----------------------------------------------------------------------

export const navConfig = [
  // {
  //   title: 'Home',
  //   path: '/',
  // },
  // {
  //   title: 'Bloqueios',
  //   path: '#bloqueios',
  // },
  // {
  //   title: 'Destinos',
  //   path: '#destinations',
  //   children: [
  //     {
  //       subheader: 'África',
  //       items: [
  //         { title: 'África do Sul', path: '/' },
  //         { title: 'Botswana', path: '/' },
  //         { title: 'Ilhas Maurício', path: '/' },
  //         { title: 'Ilhas Seychelles', path: '/' },
  //         { title: 'Marrocos', path: '/' },
  //         { title: 'Moçambique', path: '/' },
  //         { title: 'Namíbia', path: '/' },
  //         { title: 'Ruanda', path: '/' },
  //         { title: 'Quênia', path: '/' },
  //         { title: 'Tanzânia', path: '/' },
  //         { title: 'Uganda', path: '/' },
  //         { title: 'Zimbábue', path: '/' },
  //       ],
  //     },
  //     {
  //       subheader: 'América',
  //       items: [
  //         { title: 'Argentina', path: '/' },
  //         { title: 'Brasil', path: '/' },
  //         { title: 'Canadá', path: '/' },
  //         { title: 'Caribe', path: '/' },
  //         { title: 'Chile', path: '/' },
  //         { title: 'Costa Rica', path: '/' },
  //         { title: 'Estados Unidos', path: '/' },
  //         { title: 'El Salvador', path: '/' },
  //         { title: 'México', path: '/' },
  //         { title: 'Peru', path: '/' },
  //         { title: 'Uruguai', path: '/' },
  //       ],
  //     },
  //     {
  //       subheader: 'Ásia',
  //       items: [
  //         { title: 'Butão', path: '/' },
  //         { title: 'Camboja', path: '/' },
  //         { title: 'China', path: '/' },
  //         { title: 'Filipinas', path: '/' },
  //         { title: 'Ilhas Maldivas', path: '/' },
  //         { title: 'Índia', path: '/' },
  //         { title: 'Indochina', path: '/' },
  //         { title: 'Indonésia', path: '/' },
  //         { title: 'Japão', path: '/' },
  //         { title: 'Laos', path: '/' },
  //         { title: 'Nepal', path: '/' },
  //         { title: 'Singapura', path: '/' },
  //         { title: 'Sri Lanka', path: '/' },
  //         { title: 'Tailândia', path: '/' },
  //         { title: 'Tibete', path: '/' },
  //         { title: 'Vietnã', path: '/' },
  //       ],
  //     },
  //     {
  //       subheader: 'Europa',
  //       items: [
  //         { title: 'Alemanha', path: '/' },
  //         { title: 'Croácia', path: '/' },
  //         { title: 'Escandinávia', path: '/' },
  //         { title: 'Espanha', path: '/' },
  //         { title: 'França', path: '/' },
  //         { title: 'Grécia', path: '/' },
  //         { title: 'Islândia', path: '/' },
  //         { title: 'Itália', path: '/' },
  //         { title: 'Portugal', path: '/' },
  //         { title: 'Reino Unido', path: '/' },
  //         { title: 'Suíça', path: '/' },
  //         { title: 'Turquia', path: '/' },
  //       ],
  //     },
  //     {
  //       subheader: 'Oceania',
  //       items: [
  //         { title: 'Austrália', path: '/' },
  //         { title: 'Ilhas Fiji', path: '/' },
  //         { title: 'Nova Zelândia', path: '/' },
  //         { title: 'Tahiti', path: '/' },
  //       ],
  //     },
  //     {
  //       subheader: 'Oriente Médio',
  //       items: [
  //         { title: 'Emirados Árabes ', path: '/' },
  //         { title: 'Jordania', path: '/' },
  //         { title: 'Omã', path: '/' },
  //         { title: 'Qatar', path: '/' },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   title: 'Quem somos',
  //   path: '/about',
  // },
];
